# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baemin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-id',)},
        ),
    ]
